services:
  app:
    build: .
    container_name: Alaa-nest-app
    ports:
      - '${LOCAL_APP_PORT}:${LISTENING_PORT}'
    depends_on:
      - mysql
    env_file:
      - .env
    environment:
      DB_HOST: mysql
      DB_PORT: ${DATABASE_PORT}
      DB_USERNAME: ${DATABASE_USERNAME}
      DB_PASSWORD: ${DATABASE_PASSWORD}
      DB_NAME: ${DATABASE}
    volumes:
      - ./src:/app/src

  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    ports:
      - '${LOCAL_MYSQL_PORT}:3306'
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE}
    volumes:
      - mysqldata:/var/lib/mysql

volumes:
  mysqldata: