services:
  app:
    build: .
    container_name: Alaa-nest-app
    ports:
      - '8080:3000'
    depends_on:
      - mysql
    env_file:
      - .env
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USERNAME: ${DATABASE_USERNAME}
      DB_PASSWORD: ${DATABASE_PASSWORD}
      DB_NAME: ${DATABASE}
    volumes:
      - .:/app
    command: npm run start:dev

  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    ports:
      - '3307:3306'
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE}
    volumes:
      - mysqldata:/var/lib/mysql

volumes:
  mysqldata: